# Generated by Django 5.1.7 on 2025-03-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='firm_images/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
