# Generated by Django 5.1.7 on 2025-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0002_firm_description_firm_image_firm_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
