# Generated by Django 5.1.7 on 2025-03-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0006_firm_latitude_firm_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='longitude',
        ),
    ]
